Attendees Form + Suscription Process
jean-plank/tournadeck pull request #7
Opened 2023-12-18 14:36 UTC by tbocquet

2023-12-18 17:02 UTC, Gurimarukin commented on pb_migrations/1702553129_created_Attendees.js
Concernant les migrations, est-ce que tu veux bien les fusionner pour qu'il n'y en ai qu'une par table ?  
(D'accord, par la suite il y en aura plein, mais ce serait pas mal de garder les migrations atomiques par PR.)

Si non, je veux bien le faire, np.

Toutes les `createRule` sont inutiles, à mon avis, vu qu'on va gérer les permissions côté back Next.

2023-12-18 17:02 UTC, Gurimarukin commented on next.config.js
> +const nextConfig = {
Le `@type` doit rester juste au-dessus de `const nextConfig =` (pour bénéficier du typage).

Supprimer le console.log

2023-12-18 17:02 UTC, Gurimarukin commented on public/wanted-template.png
Toujours utilisé ?

2023-12-18 17:02 UTC, Gurimarukin commented on src/app/tournaments/page.tsx
> +  }, [pb])
`useSWR` + `AsyncRenderer`  ?

Pas très important, néanmoins, vu qu'on va migrer sur l'asynchrone Next (avec le SSR).

2023-12-18 17:02 UTC, Gurimarukin commented on src/app/tournaments/page.tsx
Pour moi, si l'appli est en français, il faut que le routing soit en français.
- `/tournois` : liste de tous les tournois
- `/tournoi/:id` (sans le `s`) : détails d'un tournoi

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  const validate = (newInputs: Inputs): Errors => {
À sortir du composant.

2023-12-18 17:02 UTC, Gurimarukin commented on next.config.js
> +        hostname: '127.0.0.1',
```suggestion
        hostname: url.hostname,
```

2023-12-18 17:02 UTC, Gurimarukin commented on pb_migrations/1702553129_created_Attendees.js
> +        "type": "text",
Pour moi, ça devrait être une enum `top|jun|mid|bot|sup`

2023-12-18 17:02 UTC, Gurimarukin commented on src/app/tournaments/[tournament]/page.tsx
> +  return tournamentData === null ? (
```suggestion
  const { pb } = usePocketBase()

  useEffect(() => {
    pb.collection('tournaments')
      .getOne<Tournament>(params.tournament, {})
      .then(res => {
        setTournamentData(res)
      })
  }, [params.tournament, pb])

  return tournamentData === null ? (
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +const AttendeeForm: React.FC<Props> = ({ tournamentId, onSuscribeOk }) => {
```suggestion
}

const AttendeeForm: React.FC<Props> = ({ tournamentId, onSuscribeOk }) => {
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +    //riotId
```suggestion
    // riotId
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +    // }
À supprimer ?

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  }
En début de fichier ?

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  type Errors = Partial<Record<keyof Inputs, string>>
types en début de fichier

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  type Touched = Partial<Record<keyof Inputs, boolean>>
idem

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      console.log(inputs)
log

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      console.log(user)
log

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  const [errors, setErrors] = useState<Errors>(validate(inputs))
À quoi ça sert d'avoir `errors` dans un state, vu que tu fais toujours `setInputs` en même que `setErrors`.  
Tu peux pas juste :
```suggestion
  const errors = validate(inputs)
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      }
```suggestion
        <SelectInput
          id="currentElo"
          label="Current Elo"
          value={inputs['currentElo']}
          values={[
            'Fer',
            'Bronze',
            'Argent',
            'Or',
            'Platine',
            'Emeraude',
            'Diamant',
            'Maître',
            'Grand Maître',
            'Challenger',
          ]}
          onChange={handleSelectChange('currentElo')}
          errorMsg={errors.currentElo ?? ''}
          showErrorMsg={showErrorMsg('currentElo')}
        />
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      {
pareil

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      {
pareil

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +        hover:bg-blue-700"
Toutes les classes sur la même ligne ?

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  const handleSubmit = () => (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
```suggestion
  const handleSubmit = (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +type Props = { data: Attendee }
```suggestion
type Props = {
  data: Attendee
}

```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +  <div className="relative flex w-[20rem] flex-col items-center rounded-lg border-2 border-gray-600 bg-blue-200 p-4">
```suggestion
  <div className="relative flex w-80 flex-col items-center rounded-lg border-2 border-gray-600 bg-blue-200 p-4">
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +      className="h-[15rem] w-[15rem] rounded-xl border-2 border-gray-400   object-cover object-center"
```suggestion
      className="h-60 w-60 rounded-xl border-2 border-gray-400 object-cover object-center"
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +    <div className=" z-30 font-bold ">
```suggestion
    <div className="z-30 font-bold">
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +    {/* <Image
Comment on fait pour next/image ?

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +  }, [])
```suggestion
  const handleSuscribeClick = useCallback((): void => {
    if (dialog.current !== null) dialog.current.showModal()
  }, [])

  const handleCancelClick = useCallback((): void => {
    if (dialog.current !== null) dialog.current.close()
  }, [])

  const onSuscribeOk = useCallback((): void => {
    if (dialog.current !== null) dialog.current.close()
    setSuscribed(true)
  }, [])
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +            S'inscrire
```suggestion
            S’inscrire
```

2023-12-18 17:02 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +        <h2 className="text-lg font-bold"> Intendees</h2>
```suggestion
        <h2 className="text-lg font-bold">Attendees</h2>
```

2023-12-19 10:00 UTC, tbocquet commented on pb_migrations/1702553129_created_Attendees.js
Je m'en remet à toi pour cette tache

2023-12-19 10:02 UTC, tbocquet commented on src/app/tournaments/page.tsx
> +  }, [pb])
j'attendrais la migration du coup

2023-12-19 10:08 UTC, tbocquet commented on src/components/AttendeeForm.tsx
> +  const validate = (newInputs: Inputs): Errors => {
J'ai pas compris

2023-12-19 12:41 UTC, tbocquet commented on src/components/AttendeeForm.tsx
> +      }
J'ai pas compris ce qui change

2023-12-19 12:44 UTC, tbocquet commented on src/components/AttendeeForm.tsx
> +  const handleSubmit = () => (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
Pourquoi ?

2023-12-19 12:47 UTC, tbocquet commented on src/components/AttendeeTile.tsx
> +    {/* <Image
Je sais pas et jminerve

2023-12-19 15:35 UTC, Gurimarukin requested changes

2023-12-19 15:35 UTC, Gurimarukin commented on next.config.js
> +const nextConfig = {
```suggestion
const url = new URL(process.env.NEXT_PUBLIC_POCKET_BASE_URL)

/** @type {import('next').NextConfig} */
const nextConfig = {
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  const validate = (newInputs: Inputs): Errors => {
Sors la fonction `validate` du composant.

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      }
Enlève les `{}` autour de `<SelectInput ... />`

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +  const handleSubmit = () => (event: React.MouseEvent<HTMLButtonElement, MouseEvent>) => {
Parce que ça sert à rien le `() =>`

2023-12-19 15:35 UTC, Gurimarukin commented on src/app/tournoi/[tournament]/page.tsx
> +export default function Page({ params }: { params: { tournament: string } }): JSX.Element {
```suggestion
const Page: React.FC<Props> = ({ params }) => {
```
?

2023-12-19 15:35 UTC, Gurimarukin commented on src/app/tournoi/[tournament]/page.tsx
> +    <div>Error getting tournament data</div>
```suggestion
    <div>Erreur lors de la récupération du tournoi</div>
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/app/tournois/page.tsx
> +      })
C'est un peu pour pinailler, le change pas si tu veux pas, mais tu peux faire :
```suggestion
      .then(setTournaments)
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +    }
Tu pourrais améliorer le typage en faisant : 
```suggestion
    let obj: Touched = {}
    for (const cle in inputs) {
      obj = { ...obj, [cle]: true }
    }
```
mais `cle` n'est quand même pas correctement typé, ça me plait pas :
![image](https://github.com/jean-plank/tournadeck/assets/18679417/83887c48-62bf-4b3a-a19c-6412721dd7fa)
(Je voudrais du `keyof Touched`.)


Pourquoi pas :
```suggestion
    const obj = readonlyRecord
      .keys(inputs)
      .reduce<Touched>((acc, key) => ({ ...acc, [key]: true }), {})
```
?

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      noValidate={true}
```suggestion
      onSubmit={handleSubmit}
```
et change le `type` du `button` de soumission à `type="submit"` (et enlève le `onClick` dudit bouton).

Sauf erreur, tu auras besoin d'ajouter un `e.preventDefault()` dans le `handleSubmit`, mais essaye sans.

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +          label="Current Elo"
"Classement actuel" ? "Elo actuel" ?

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +        placeholder="c'est à cause de mes mates !"
```suggestion
        placeholder="C'est à cause de mes mates !"
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +            'Ça fait beaucoup la non',
```suggestion
            'Ça fait beaucoup là non',
```

De plus, peut-être pas en faire un `select` en base, mais en faire une union en TS ?

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +          label="Role"
```suggestion
          label="Rôle"
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +          label="Champion Pool"
```suggestion
          label="Pool de champions"
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +        label="Birthplace"
```suggestion
        label="Lieu de naissance"
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +        placeholder="birthPlace"
```suggestion
        placeholder="Lieu de naissance"
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +        placeholder="avatar"
Est-ce que c'est à tourner en mode rigolo : "photo de votre épouvantable faciès" ?

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +export const AttendeeTile: React.FC<Props> = ({ data }: Props) => (
Juste 
```suggestion
export const AttendeeTile: React.FC<Props> = ({ data }) => (
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
Le dossier `components`, c'est pour les composants génériques/réutilisables.  
Le dossier `domain`, c'est pour les composants qui pourraient être dans `app`, sauf qu'on les met pas dans `app`, pour pas polluer `app` (comme ça, `app` sert juste à représenter le routeur et reste lisible).


Donc `TournamentTile` va dans `domain/tournois` (je me dis que c'est logique de refléter la structure de `app`, mais c'est peut-être une idée de merde).  
Et `AttendeeForm`, `AttendeeTile` et `TournamentFC` vont dans `domain/tournoi/[tournament]`.

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +export default AttendeeForm
Pas d'`export default` (parce que VSCode gère pas bien l'import et le renommage), sauf dans `app`, parce qu'on est obligé.

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/AttendeeTile.tsx
> +    {/* <Image
Je vais regarder.

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/FormInputs.tsx
> +      <label htmlFor={id} className="font-semibold ">
Je m'oppose au `htmlFor`. Je vois pas pourquoi j'aurais besoin de spécifier un *id de merde* quand je veux faire un input.  
Plutôt que de faire :
```ts
<div>
  <label htmlFor="id">{label}</label>
  <input id="id />
</div>
```
tu peut faire
```ts
<label>
  <span>{label}</span>
  <input />
</label>
```
et ça marche et ça se style exactement pareil

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/FormInputs.tsx
> +      <label htmlFor={id} className="font-semibold ">
```suggestion
      <label htmlFor={id} className="font-semibold">
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/FormInputs.tsx
> +      <label htmlFor={id} className="font-semibold ">
```suggestion
      <label htmlFor={id} className="font-semibold">
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/FormInputs.tsx
> +      <label htmlFor={id} className="font-semibold ">
```suggestion
      <label htmlFor={id} className="font-semibold">
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +  //Check si l'utilisateur est déjà inscrit
```suggestion
  // check if user register
```
en anglais dans le code, en français dans l'appli et le routing

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +type Props = { data: Tournament }
```suggestion
type Props = {
  data: Tournament
}

```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +export const TournamentFC: React.FC<Props> = ({ data }: Props) => {
```suggestion
export const TournamentFC: React.FC<Props> = ({ data }) => {
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +        <div>Debut : {data.end}</div>
```suggestion
        <div>Début : {data.start}</div>
        <div>Fin : {data.end}</div>
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +            type="submit"
```suggestion
            type="button"
```
Pourquoi t'as un bouton `submit` en dehors d'un `form` ?

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +            className="w-[5rem] bg-black text-white"
```suggestion
            className="w-20 bg-black text-white"
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +            <button className="cursor-pointer p-2" type="submit" onClick={handleCancelClick}>
```suggestion
            <button type="button" className="cursor-pointer p-2" onClick={handleCancelClick}>
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentFC.tsx
> +              cancel
```suggestion
              Annuler
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentTile.tsx
> +    <div>Debut : {data.end}</div>
```suggestion
    <div>Début : {data.start}</div>
    <div>Fin : {data.end}</div>
```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentTile.tsx
> +type Props = { data: Tournament }
```suggestion
type Props = {
  data: Tournament
}

```

2023-12-19 15:35 UTC, Gurimarukin commented on src/components/TournamentTile.tsx
> +export const TournamentTile: React.FC<Props> = ({ data }: Props) => (
```suggestion
export const TournamentTile: React.FC<Props> = ({ data }) => (
```

2023-12-19 20:20 UTC, tbocquet commented on src/components/AttendeeForm.tsx
> +    }
C'est pas un peu overkill

2023-12-19 20:30 UTC, tbocquet commented on src/components/AttendeeForm.tsx
> +      noValidate={true}
Ok j'ai pas réussi à faire fonctionner avec le bouton passé en type submit 
On verra ça

2023-12-19 20:45 UTC, tbocquet commented on src/components/FormInputs.tsx
> +      <label htmlFor={id} className="font-semibold ">
ça va trop loin

2023-12-19 20:47 UTC, tbocquet commented on src/components/TournamentFC.tsx
> +type Props = { data: Tournament }
Mais ça c'est un vrai truc ou c'est juste toi ?

2023-12-20 14:05 UTC, Gurimarukin requested changes

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeTile.tsx
> +      className="h-60 w-60 rounded-xl border-2 border-gray-400   object-cover object-center"
```suggestion
      className="h-60 w-60 rounded-xl border-2 border-gray-400 object-cover object-center"
```

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeTile.tsx
> +      <div className="">Piscine de champions : {data.championPool}</div>
```suggestion
      <div>Niveau actuel : {data.currentElo}</div>
      <div>PeakElo : {data.comment}</div>
      <div>Rôle : {data.role}</div>
      <div>Piscine de champions : {data.championPool}</div>
```

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeForm.tsx
> +      className="flex w-[26rem] flex-col gap-3 rounded-lg border-2 border-gray-400 bg-white p-4"
Plutôt que de hard-coder `w-[26rem]` (déjà, je trouve `w-[416px]` plus clair), il serait plus défensif de faire : `min-w-[416px]`

[Defensive CSS](https://ishadeed.com/article/defensive-css)

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeTile.tsx
> +/* eslint-disable @next/next/no-img-element */
Plutôt que de le désactiver pour tout le fichier, je trouve mieux de le désactiver juste là où est l'erreur.

2023-12-20 14:05 UTC, Gurimarukin commented on next.config.js
> +const url = new URL(process.env.NEXT_PUBLIC_POCKET_BASE_URL)
```suggestion
const url = new URL(process.env.NEXT_PUBLIC_POCKET_BASE_URL)

```

2023-12-20 14:05 UTC, Gurimarukin commented on next.config.js
> +}
```suggestion
}

```

2023-12-20 14:05 UTC, Gurimarukin commented on src/app/tournoi/[tournament]/page.tsx
> +const Page: React.FC<Props> = ({ params }) => {
```suggestion
}

const TournamentPage: React.FC<Props> = ({ params }) => {
```

2023-12-20 14:05 UTC, Gurimarukin commented on src/app/tournois/page.tsx
> +const TournamentSuscription: React.FC = () => {
```suggestion
const Tournaments: React.FC = () => {
```

2023-12-20 14:05 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +    }
C'est plus propre, je trouve.  
J'aurais dû interdire les `for` et `while`.

2023-12-20 14:05 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +      noValidate={true}
Là partie importante, c'est `onSubmit={handleSubmit}` sur le `<form>`.  
Ça rend le formulaire plus accessible (tu peux le soumettre en appuyant sur Entrer depuis un `<input>`).

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeForm.tsx
> +import { comment } from 'postcss'
```suggestion
```
Et ligne 38 :
```ts
  if (newInputs.comment.length > 50) {
```

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeForm.tsx
> +  const riotIdRegex = /^.{4,16}#[a-zA-Z0-9]{3,5}$/
Tu peux sortir la regex pour qu'elle soit pas redéclarée à chaque appel (ça a un certain coût).

2023-12-20 14:05 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
> +            'Ça fait beaucoup la non',
Une union TS pour cette piscine de champions ?

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeForm.tsx
> +          'Une compétence cheval',
```suggestion
          'Un seul poney à mon arc',
```

2023-12-20 14:05 UTC, Gurimarukin commented on src/components/AttendeeForm.tsx
En vrai, je regarde l'arborescence, je me dis que tout pourrait aller dans `domain/tournament/` (désolé) :
![image](https://github.com/jean-plank/tournadeck/assets/18679417/346b8266-5803-43fa-a589-8c8136fec068)

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournois/TournamentTile.tsx
> +  <div className="w-80 rounded-lg bg-blue-200 p-3 hover:cursor-pointer hover:bg-sky-300">
```suggestion
  <div className="w-80 rounded-lg bg-blue-200 p-3 cursor-pointer hover:bg-sky-300">
```
Redondant. `cursor-pointer`, c'est forcément au hover.

2023-12-20 14:05 UTC, Gurimarukin commented on src/domain/tournoi/AttendeeForm.tsx
> +        Validate
```suggestion
        Valider
```

2023-12-21 11:30 UTC, tbocquet commented on src/components/AttendeeForm.tsx
> +    }
Les restrictions liées au covid 19

2023-12-22 08:11 UTC, Gurimarukin commented on pb_migrations/1702553129_created_Attendees.js
Commencé dans une autre PR.  
Faudra supprimer les migrations de celle-ci avant de merge.

2023-12-24 18:16 UTC, Gurimarukin approved these changes

2023-12-24 22:32 UTC, merged